language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# Email Push after CI Complete
notifications:
  email:
    recipients:
      - "yh0921k@naver.com"

before_deploy:
  - zip -r springboot *
  - mkdir -p deploy
  - mv springboot.zip deploy/springboot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Registered Value in Travis CI
    secret_access_key: $AWS_SECRET_KEY # Registered Value in Travis CI
    bucket: kyh-springboot-build # S3 Bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # Auth to access zip file is private
    local_dir: deploy # Directory Name above before_deploy makes
    wait-until-deployed: true