language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# Email Push after CI Complete
notifications:
  email:
    recipients:
      - "yh0921k@naver.com"

before_deploy:
  - zip -r springboot *
  - mkdir -p deploy
  - mv springboot.zip deploy/springboot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Registered Value in Travis CI
    secret_access_key: $AWS_SECRET_KEY # Registered Value in Travis CI
    bucket: kyh-springboot-build # S3 Bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # Auth to access zip file is private
    local_dir: deploy # Directory Name above before_deploy makes
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis Repo Settings에 설정한 값
    secret_access_key: $AWS_SECRET_KEY # Travis Repo Settings에 설정한 값
    bucket: kyh-springboot-build # S3 Bucket
    key: springboot.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: springboot # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springboot_group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

