spring:
  profiles:
    include: oauth
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true # 한줄에 보이던 sql을 pretty
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc

#server:
#  port: 80

# 주석