spring:
  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true # 한줄에 보이던 sql을 pretty
  h2:
    console:
      enabled: true

#server:
#  port: 80

# 주석