drop table posts if exists
drop table user if exists

create table posts (
   id bigint generated by default as identity,
    created_date timestamp,
    modified_date timestamp,
    author varchar(255),
    content TEXT not null,
    title varchar(500) not null,
    primary key (id)
)

create table user (
   id bigint generated by default as identity,
    created_date timestamp,
    modified_date timestamp,
    email varchar(255) not null,
    name varchar(255) not null,
    picture varchar(255),
    role varchar(255) not null,
    primary key (id)
)